# Generated by Django 2.0.2 on 2018-04-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=32)),
                ('subs', models.TextField(default='简介')),
                ('content', models.TextField(null=True)),
                ('email', models.EmailField(default='xxxx@xx.com', max_length=75)),
                ('image', models.ImageField(default='none', upload_to=None)),
                ('author', models.CharField(default='佚名', max_length=24)),
                ('pagetime', models.DateField(default='none')),
                ('tag', models.CharField(default='普通', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='BlogIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='iconname', max_length=24)),
                ('title', models.CharField(default='介绍', max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
