# Generated by Django 2.0.2 on 2018-04-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pagetime',
            field=models.DateField(default='xxx'),
        ),
    ]
