# Generated by Django 2.0.2 on 2018-04-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180414_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='佚名', max_length=24)),
                ('sex', models.NullBooleanField()),
                ('ace', models.NullBooleanField()),
                ('email', models.EmailField(default='xxxx@xx.com', max_length=75)),
                ('avatar', models.ImageField(upload_to='')),
                ('description', models.TextField(default='这个人很懒，啥都没说！')),
                ('passagenum', models.IntegerField()),
                ('fansnum', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='none', upload_to='photos'),
        ),
    ]
