# Generated by Django 2.0.2 on 2018-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180415_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='op',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
